name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: rust:latest 
    permissions:
      contents: write  # To push a branch 
      pull-requests: write  # To create a PR from that branch
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: build env
      run:  |
        cargo install mdbook
        cargo install mdbook-katex
    - name: deploy
      run:  |
        mdbook build
        git worktree add gh-pages
        git config user.name "Xrtero"
        git config user.email "xrtero@gmail.com"
        cd gh-pages
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        rm -rf *
        mv ../book/* .
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages
